services:
  - type: web
    name: mon-kine-blazor
    env: docker
    branch: main
    repo: https://github.com/Baniero/Mon-Kin-.git
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d9odl6vlk1mc738coipg-a
          property: DATABASE_URL
    healthCheckPath: "/"
    plan: starter
    region: oregon
