services:
  - type: web
    name: mon-kine-blazor
    env: dotnet
    branch: master
    repo: https://github.com/Baniero/Mon-Kin-.git
    buildCommand: dotnet publish MonKineBlazor.Server/MonKineBlazor.Server.csproj -c Release -o publish
    startCommand: dotnet publish/MonKineBlazor.Server.dll
    envVars:
      - key: DATABASE_URL
        value: "postgres://<username>:<password>@<host>:<port>/<database>"
        fromDatabase: false
    healthCheckPath: "/"
    plan: starter
    region: oregon
