services:
  - type: web
    name: mon-kine-blazor
    env: docker
    branch: master
    repo: https://github.com/Baniero/Mon-Kin-.git
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgres://<username>:<password>@<host>:<port>/<database>"
        fromDatabase: false
    healthCheckPath: "/"
    plan: starter
    region: oregon
